### ISSUE TITLE
compatability with melonslabs

### ISSUE THREAD

**Issue by milkev** [Eilux/BetterSlabs#1]
compatability issue with melon slabs. removing melon slabs or betterslabs has no issues. if this is something that needs to be fixed on melonslabs end ill post an issue there.

it doesnt make a crash report, i had to copy & paste out of the log/console. sorry.
tried with both the 1.16.2 and 1.16.3 versions on 1.16.2

https://pastebin.com/SCsSyLhQ

**Comment by Eilux** [comment]
Two things:
1. Can you provide a link to this mod
2. Could you describe what exactly happened when you loaded both together

**Comment by milkev** [comment]
https://www.curseforge.com/minecraft/mc-mods/melon-slabs

the game crashed before the game window even opened. i provided a copy & paste from the log since it didnt provide a crash report file.

**Comment by Eilux** [comment]
Hmm I w I’ll look into it

**Comment by Eilux** [comment]
Regrettably I will not be able to fix this, because they override the method appendProperties (this method has all blockstates in it) and their version does not include the blockstate type of my mod, causing it to crash. I doubt there is anything they could do about it either (unless they made my mod a dependency)
